### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by binyamin** [MakerDotRocks/frontend#1]
What is the license for this project? I'd like to know where and how my code will be used in the future before I contribute. I mostly use the [MIT license](https://opensource.org/licenses/MIT), but it's up to you.

**Comment by Booligoosh** [comment]
Hi, sorry I only just saw this!

I have added a license, you can view the TL;DR here:
https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by Booligoosh** [comment]
I think it should be fine, but let me know if you have any issues with it BTW
